name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
    
env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build_apk_aab:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build release APK and AAB after test
      run: |
         ./gradlew test
         ./gradlew assembleRelease
         ./gradlew bundleRelease
         
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
         name: app-release.apk
         path: app/build/outputs/apk/release/app-release.apk
    - name: Upload AAB Bundle
      uses: actions/upload-artifact@v2
      with:
        name: app-release.aab
        path: app/build/outputs/bundle/release/app-release.aab 
